{
 "title": "Qdrant",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "qdrant_node", "query": { "query": "label_values(app_info,node)" } },
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_info>0)", "legendFormat": "node-count" }
   ]
  },
  { "title": "GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Responses Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(grpc_responses_total{node=~\"${node}\",app=\"qdrant\"}[2m])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(grpc_responses_fail_total{node=~\"${node}\",app=\"qdrant\"}[2m])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "grpc_responses_avg_duration_seconds{node=~\"${node}\",app=\"qdrant\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "grpc_responses_min_duration_seconds{node=~\"${node}\",app=\"qdrant\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "grpc_responses_max_duration_seconds{node=~\"${node}\",app=\"qdrant\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency for \"${node}\" node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(grpc_responses_avg_duration_seconds{node=~\"${node}\",app=\"qdrant\"}) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Minimum Latency for \"${node}\" node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(grpc_responses_min_duration_seconds{node=~\"${node}\",app=\"qdrant\"}) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Maximum Latency for \"${node}\" node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(grpc_responses_max_duration_seconds{node=~\"${node}\",app=\"qdrant\"}) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "REST API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Responses Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(rest_responses_total{node=~\"${node}\",app=\"qdrant\"}[2m])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Responses Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(rest_responses_fail_total{node=~\"${node}\",app=\"qdrant\"}[2m])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rest_responses_avg_duration_seconds{node=~\"${node}\",app=\"qdrant\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rest_responses_min_duration_seconds{node=~\"${node}\",app=\"qdrant\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rest_responses_max_duration_seconds{node=~\"${node}\",app=\"qdrant\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency for \"${node}\" node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rest_responses_avg_duration_seconds{node=~\"${node}\",app=\"qdrant\"}) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Minimum Latency for \"${node}\" node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rest_responses_min_duration_seconds{node=~\"${node}\",app=\"qdrant\"}) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Maximum Latency for \"${node}\" node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rest_responses_max_duration_seconds{node=~\"${node}\",app=\"qdrant\"}) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Cluster Related Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true
  }
 ]
}