apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.alioth.aliothIngest.fullname }}
  labels:
    helm.sh/chart: {{ include "alioth.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ .Values.alioth.aliothIngest.fullname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    checksum/config.files: {{ include (print $.Template.BasePath "/configmap.alioth.files.yaml") . | sha256sum }}
    checksum/secret: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
spec:
  {{- if not .Values.alioth.aliothIngest.autoscaling.enabled }}
  replicas: {{ .Values.alioth.aliothIngest.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.alioth.aliothIngest.fullname }}
  template:
    metadata:
      {{- with .Values.alioth.aliothIngest.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Values.alioth.aliothIngest.fullname }}
    spec:
      {{- with .Values.alioth.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alioth.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.alioth.aliothIngest.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.alioth.aliothIngest.fullname }}
          securityContext:
            {{- toYaml .Values.alioth.aliothIngest.securityContext | nindent 12 }}
          image: "{{ .Values.alioth.image.repository }}:{{ .Values.alioth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.alioth.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "make spawn-ingestion-celery-worker"]
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config
            - secretRef:
                name: {{ .Chart.Name }}-secret
          volumeMounts:
            - name: config-files
              mountPath: /config
          resources:
            {{- toYaml .Values.alioth.aliothIngest.resources | nindent 12 }}
      volumes:
        - name: config-files
          configMap:
            name: {{ .Chart.Name }}-config-files
      {{- with .Values.alioth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alioth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alioth.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
