apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
stringData:
  QDRANT_DB_HOST: qdrant.{{ .Release.Namespace }}.svc.cluster.local
  QDRANT_DB_PORT: "6333"
  QDRANT_DB_GRPC_PORT: "6334"
  QDRANT_DB_PROTO: http
  BROKER_PROTO: amqp
  BROKER_HOST: rabbitmq.{{ .Release.Namespace }}.svc.cluster.local
  BROKER_PORT: "5672"
  BROKER_USER: user
  BROKER_PASS: supersecret
  AWS_ACCESS_KEY: minio
  AWS_SECRET_KEY: supersecret
  AWS_ENDPOINT_URL: http://minio.{{ .Release.Namespace }}.svc.cluster.local:9000
  S3_BUCKET_NAME: alioth