{{- if .Values.alioth.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alioth.serviceAccountName" . }}
  labels:
    {{- include "alioth.labels" . | nindent 4 }}
  {{- with .Values.alioth.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
