apiVersion: v1
kind: Service
metadata:
  name: {{ include "alioth.fullname" . }}
  labels:
    {{- include "alioth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.alioth.service.type }}
  ports:
    - port: {{ .Values.alioth.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "alioth.selectorLabels" . | nindent 4 }}
