apiVersion: v1
appVersion: v0.0.1
version: 1.0.0
name: alioth
description: Ingest data at scale
home: https://github.com/coolfool/alioth
maintainers:
- email: hello@coolfool.me
  name: CoolFool
sources:
- https://github.com/coolfool/alioth
dependencies:
  - name: rabbitmq
    version: "12.1.3"
    repository: file://charts/rabbitmq
  - name: qdrant
    version: "0.4.1"
    repository: file://charts/qdrant
  - name: minio
    version: "5.0.13"
    repository: file://charts/minio
  - name: prometheus
    version: "24.3.0"
    repository: file://charts/prometheus
  - name: grafana
    version: "6.59.1"
    repository: file://charts/grafana
  - name: celery-exporter
    version: "0.6.5"
    repository: file://charts/celery-exporter
  - name: prometheus-statsd-exporter
    version: "0.10.0"
    repository: file://charts/prometheus-statsd-exporter
