name: CI
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag & repo name for PR builds
        if: ${{ !contains(fromJson('["refs/heads/master" ]'), github.ref) && !startsWith(github.event.ref, 'refs/tags/v') }}
        run: |
          echo "IMAGE_TAG=PR-${{ github.event.number }}" >> $GITHUB_ENV
    
      - name: Set tag & repo name for master builds
        if: contains(fromJson('["refs/heads/master"]'), github.ref)
        run: |
          echo "IMAGE_TAG=main" >> $GITHUB_ENV
    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/coolfool/alioth/:${{ env.IMAGE_TAG }}
      